# Used Car Price Prediction

## 1) Problem statement.

* This dataset comprises used cars sold on cardehko.com in India as well as important features of these cars.
* If user can predict the price of the car based on input features.
* Prediction results can be used to give new seller the price suggestion based on market condition.

## 2) Data Collection.
* The Dataset is collected from scrapping from cardheko webiste
* The data consists of 13 column and 15411 rows.

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings
warnings.filterwarnings("ignore")

In [7]:
df = pd.read_csv(r"data/cardekho_imputated.csv", index_col=[0])

In [8]:
df

              car_name     brand     model  ...  max_power  seats selling_price
0          Maruti Alto    Maruti      Alto  ...      46.30      5        120000
1        Hyundai Grand   Hyundai     Grand  ...      82.00      5        550000
2          Hyundai i20   Hyundai       i20  ...      80.00      5        215000
3          Maruti Alto    Maruti      Alto  ...      67.10      5        226000
4        Ford Ecosport      Ford  Ecosport  ...      98.59      5        570000
...                ...       ...       ...  ...        ...    ...           ...
19537      Hyundai i10   Hyundai       i10  ...      68.05      5        250000
19540    Maruti Ertiga    Maruti    Ertiga  ...      91.10      7        925000
19541      Skoda Rapid     Skoda     Rapid  ...     103.52      5        425000
19542  Mahindra XUV500  Mahindra    XUV500  ...     140.00      7       1225000
19543       Honda City     Honda      City  ...     117.60      5       1200000

[15411 rows x 13 columns]

## Data Cleaning
### Handling Missing values

* Handling Missing values 
* Handling Duplicates
* Check data type
* Understand the dataset

In [9]:
## Check null values

df.isnull().sum()

car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [10]:
## Remove Unnecessary columns
df.drop(columns=['car_name','brand'], inplace=True)

In [11]:
df['model'].unique()

<ArrowStringArray>
[        'Alto',        'Grand',          'i20',     'Ecosport',
      'Wagon R',          'i10',        'Venue',        'Swift',
        'Verna',       'Duster',
 ...
     'Panamera',      'Alturas',       'Altroz',           'NX',
     'Carnival',            'C',           'RX',        'Ghost',
 'Quattroporte',       'Gurkha']
Length: 120, dtype: str

In [12]:
df.head()

      model  vehicle_age  km_driven  ... max_power seats selling_price
0      Alto            9     120000  ...     46.30     5        120000
1     Grand            5      20000  ...     82.00     5        550000
2       i20           11      60000  ...     80.00     5        215000
3      Alto            9      37000  ...     67.10     5        226000
4  Ecosport            6      30000  ...     98.59     5        570000

[5 rows x 11 columns]

##### Checking count of features

In [13]:
## Numerical Features 

numerical_features = [features for features in df.columns if df[features].dtype != 'str']
print("Numerical Features:", len(numerical_features))

## Categorical Features 
categorical_features = [features for features in df.columns if df[features].dtype == 'str']
print("Categorical Features:",len(categorical_features))

## Discrete Features 
discrete_features = [features for features in numerical_features if len(df[features].unique()) <= 25]
print("Discrete Features:",len(discrete_features))

## Continuous Features 
continuous_features = [features for features in numerical_features if features not in discrete_features]
print("Continuous Features:",len(continuous_features))

Numerical Features: 7
Categorical Features: 4
Discrete Features: 2
Continuous Features: 5

### Independent and Dependent Features

In [14]:
X=df.drop(['selling_price'],axis=1)
y=df['selling_price']

In [15]:
X

          model  vehicle_age  km_driven  ... engine max_power seats
0          Alto            9     120000  ...    796     46.30     5
1         Grand            5      20000  ...   1197     82.00     5
2           i20           11      60000  ...   1197     80.00     5
3          Alto            9      37000  ...    998     67.10     5
4      Ecosport            6      30000  ...   1498     98.59     5
...         ...          ...        ...  ...    ...       ...   ...
19537       i10            9      10723  ...   1086     68.05     5
19540    Ertiga            2      18000  ...   1373     91.10     7
19541     Rapid            6      67000  ...   1498    103.52     5
19542    XUV500            5    3800000  ...   2179    140.00     7
19543      City            2      13000  ...   1497    117.60     5

[15411 rows x 10 columns]

In [16]:
y

0         120000
1         550000
2         215000
3         226000
4         570000
          ...
19537     250000
19540     925000
19541     425000
19542    1225000
19543    1200000
Name: selling_price, Length: 15411, dtype: int64

## Feature Encoding and Scaling
* One Hot Encoding for Columns which had lesser unique values and not ordinal 
* One hot encoding is a process by which categorical variables are converted into a form that could be provided to ML algorithms to do a better job in prediction.

In [17]:
len(df['model'].unique())

120

In [18]:
df['model'].value_counts()

model
i20             906
Swift Dzire     890
Swift           781
Alto            778
City            757
               ...
Altroz            1
C                 1
Ghost             1
Quattroporte      1
Gurkha            1
Name: count, Length: 120, dtype: int64

#### Encoding

In [19]:
from sklearn.preprocessing import LabelEncoder

lbl_encoder = LabelEncoder()
X['model'] = lbl_encoder.fit_transform(X['model'])
# X['car_name'] = lbl_encoder.fit_transform(X['car_name'])    # Drop if required
# X['brand'] = lbl_encoder.fit_transform(X['brand'])          # Drop if required

In [20]:
X

       model  vehicle_age  km_driven  ... engine max_power seats
0          7            9     120000  ...    796     46.30     5
1         54            5      20000  ...   1197     82.00     5
2        118           11      60000  ...   1197     80.00     5
3          7            9      37000  ...    998     67.10     5
4         38            6      30000  ...   1498     98.59     5
...      ...          ...        ...  ...    ...       ...   ...
19537    117            9      10723  ...   1086     68.05     5
19540     42            2      18000  ...   1373     91.10     7
19541     77            6      67000  ...   1498    103.52     5
19542    114            5    3800000  ...   2179    140.00     7
19543     25            2      13000  ...   1497    117.60     5

[15411 rows x 10 columns]

#### Encoding - Transformers

In [21]:
num_features = X.select_dtypes(exclude='str').columns
cat_features = X.select_dtypes(include='str').columns

from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

# StandardScaler is generally not needed in Random Forest
# ColumnTransformer is used were multiple transformer application is required

numeric_transformer = StandardScaler()
oh_transformer = OneHotEncoder(drop='first')

# preprocessor is the transformation
preprocessor = ColumnTransformer(
    [
        ("Standart Scaler", numeric_transformer, num_features),
        ("One Hot Encoder", oh_transformer, cat_features),
    ], remainder='passthrough'
)

In [22]:
preprocessor

ColumnTransformer(remainder='passthrough',
                  transformers=[('Standart Scaler', StandardScaler(),
                                 Index(['model', 'vehicle_age', 'km_driven', 'mileage', 'engine', 'max_power',
       'seats'],
      dtype='str')),
                                ('One Hot Encoder', OneHotEncoder(drop='first'),
                                 Index(['seller_type', 'fuel_type', 'transmission_type'], dtype='str'))])

##### Fit Transform on X

In [23]:
X=preprocessor.fit_transform(X)

In [24]:
pd.DataFrame(X)

             0         1          2         3   ...   10   11   12   13
0     -1.519714  0.983562   1.247335 -0.000276  ...  0.0  0.0  1.0  1.0
1     -0.225693 -0.343933  -0.690016 -0.192071  ...  0.0  0.0  1.0  1.0
2      1.536377  1.647309   0.084924 -0.647583  ...  0.0  0.0  1.0  1.0
3     -1.519714  0.983562  -0.360667  0.292211  ...  0.0  0.0  1.0  1.0
4     -0.666211 -0.012060  -0.496281  0.735736  ...  0.0  0.0  0.0  1.0
...         ...       ...        ...       ...  ...  ...  ...  ...  ...
15406  1.508844  0.983562  -0.869744  0.026096  ...  0.0  0.0  1.0  1.0
15407 -0.556082 -1.339555  -0.728763 -0.527711  ...  0.0  0.0  1.0  1.0
15408  0.407551 -0.012060   0.220539  0.344954  ...  0.0  0.0  0.0  1.0
15409  1.426247 -0.343933  72.541850 -0.887326  ...  0.0  0.0  0.0  1.0
15410 -1.024131 -1.339555  -0.825631 -0.407839  ...  0.0  0.0  1.0  0.0

[15411 rows x 14 columns]

### Train Test Split

In [25]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

## Model Training and Selection

In [26]:
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

Def Metrics

In [27]:
def evaluate_model(true_value, predicted_value):
    mse = mean_squared_error(true_value, predicted_value)
    mae = mean_absolute_error(true_value, predicted_value)
    rmse = np.sqrt(mean_squared_error(true_value, predicted_value))
    r2_scr = r2_score(true_value, predicted_value)
    return mse, mae, rmse, r2_scr

Model Selection and Training

In [28]:
models = {
    "Linear Regression": LinearRegression(),
    "Ridge": Ridge(),
    "Lasso": Lasso(),
    "K Nearest Neighbours": KNeighborsRegressor(),
    "Decision Tree": DecisionTreeRegressor(),
    "Random Forest Regression": RandomForestRegressor(),
    "Adaboost Regressor": AdaBoostRegressor()
}

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train,y_train)          # Train Model

    ## Prediction
    y_train_prediction = model.predict(X_train)
    y_test_prediction = model.predict(X_test)

    ## Evaluate Model
    mse_train, mae_train, rmse_train, r2_scr_train = evaluate_model(y_train, y_train_prediction)
    mse_test, mae_test, rmse_test, r2_scr_test = evaluate_model(y_test, y_test_prediction)

    print(list(models.keys())[i])

    print("-"*35)

    print("Model Performance for Training dataset")
    print("- Mean Squared Error: {:.2f}".format(mse_train))
    print("- Mean Absolute Error: {:.2f}".format(mae_train))
    print("- Root Mean Squared Error: {:.2f}".format(rmse_train))
    print("- R2 Score: {:.2f}".format(r2_scr_train))

    print("-"*35)

    print("Model Performance for Test dataset")
    print("- Mean Squared Error: {:.2f}".format(mse_test))
    print("- Mean Absolute Error: {:.2f}".format(mae_test))
    print("- Root Mean Squared Error: {:.2f}".format(rmse_test))
    print("- R2 Score: {:.2f}".format(r2_scr_test))
    print("-"*35)
    print("\n")

Linear Regression
-----------------------------------
Model Performance for Training dataset
- Mean Squared Error: 306756099359.76
- Mean Absolute Error: 268101.61
- Root Mean Squared Error: 553855.67
- R2 Score: 0.62
-----------------------------------
Model Performance for Test dataset
- Mean Squared Error: 252550062888.57
- Mean Absolute Error: 279618.58
- Root Mean Squared Error: 502543.59
- R2 Score: 0.66
-----------------------------------


Ridge
-----------------------------------
Model Performance for Training dataset
- Mean Squared Error: 306756818740.93
- Mean Absolute Error: 268059.80
- Root Mean Squared Error: 553856.32
- R2 Score: 0.62
-----------------------------------
Model Performance for Test dataset
- Mean Squared Error: 252540243247.97
- Mean Absolute Error: 279557.22
- Root Mean Squared Error: 502533.82
- R2 Score: 0.66
-----------------------------------


Lasso
-----------------------------------
Model Performance for Training dataset
- Mean Squared Error: 306756104248.64
- Mean Absolute Error: 268099.22
- Root Mean Squared Error: 553855.67
- R2 Score: 0.62
-----------------------------------
Model Performance for Test dataset
- Mean Squared Error: 252549134941.56
- Mean Absolute Error: 279614.75
- Root Mean Squared Error: 502542.67
- R2 Score: 0.66
-----------------------------------


K Nearest Neighbours
-----------------------------------
Model Performance for Training dataset
- Mean Squared Error: 106198764065.54
- Mean Absolute Error: 91396.71
- Root Mean Squared Error: 325881.52
- R2 Score: 0.87
-----------------------------------
Model Performance for Test dataset
- Mean Squared Error: 64079155016.42
- Mean Absolute Error: 112578.24
- Root Mean Squared Error: 253138.61
- R2 Score: 0.91
-----------------------------------


Decision Tree
-----------------------------------
Model Performance for Training dataset
- Mean Squared Error: 432524990.54
- Mean Absolute Error: 5164.82
- Root Mean Squared Error: 20797.24
- R2 Score: 1.00
-----------------------------------
Model Performance for Test dataset
- Mean Squared Error: 100870646771.48
- Mean Absolute Error: 127888.44
- Root Mean Squared Error: 317601.40
- R2 Score: 0.87
-----------------------------------


Random Forest Regression
-----------------------------------
Model Performance for Training dataset
- Mean Squared Error: 13552155602.49
- Mean Absolute Error: 39443.65
- Root Mean Squared Error: 116413.73
- R2 Score: 0.98
-----------------------------------
Model Performance for Test dataset
- Mean Squared Error: 52435028579.09
- Mean Absolute Error: 102008.51
- Root Mean Squared Error: 228986.96
- R2 Score: 0.93
-----------------------------------


Adaboost Regressor
-----------------------------------
Model Performance for Training dataset
- Mean Squared Error: 175509791130.61
- Mean Absolute Error: 302245.74
- Root Mean Squared Error: 418938.89
- R2 Score: 0.78
-----------------------------------
Model Performance for Test dataset
- Mean Squared Error: 207138247435.94
- Mean Absolute Error: 322898.52
- Root Mean Squared Error: 455124.43
- R2 Score: 0.72
-----------------------------------

Observation: Random Forest Performed best and the second best is K Nearest Neighbour so we will hyper parameter tune the two models

Setup Hyper Parameters for KNN and RF

In [29]:
knn_params = {"n_neighbors":[2, 3, 10, 20, 40, 501]}
rf_params = {
    "max_depth": [5, 8, 15, None, 101],
    "max_features": [5, 7, "auto", 8],
    "min_samples_split": [2, 8, 15, 20],
    "n_estimators": [100, 200, 500, 1000]
}

ada_params={
    "n_estimators":[50,60,70,80],
    "loss":['linear','square','exponential']
}

Setup randomCV

In [30]:
randomcv_models = [
    ("KNN", KNeighborsRegressor(), knn_params),
    ("Random Forest", RandomForestRegressor(), rf_params),
    ("Adaboost Regressor", AdaBoostRegressor(), ada_params)
]

Initialize RandomSearchCV

In [31]:
from sklearn.model_selection import RandomizedSearchCV

model_params={}
for name, model, params in randomcv_models:
    random = RandomizedSearchCV(estimator=model,param_distributions=params, n_iter=100, cv=3, verbose=2, n_jobs=1)

    # Model Training
    random.fit(X_train,y_train)
    model_params[name] = random.best_params_

for model_name in model_params:
    print(f"------------------------------- Best Params for {model_name} -------------------------------")
    print(model_params[model_name])

Fitting 3 folds for each of 6 candidates, totalling 18 fits
[CV] END ......................................n_neighbors=2; total time=   0.0s
[CV] END ......................................n_neighbors=2; total time=   0.0s
[CV] END ......................................n_neighbors=2; total time=   0.0s
[CV] END ......................................n_neighbors=3; total time=   0.0s
[CV] END ......................................n_neighbors=3; total time=   0.0s
[CV] END ......................................n_neighbors=3; total time=   0.0s
[CV] END .....................................n_neighbors=10; total time=   0.1s
[CV] END .....................................n_neighbors=10; total time=   0.1s
[CV] END .....................................n_neighbors=10; total time=   0.1s
[CV] END .....................................n_neighbors=20; total time=   0.1s
[CV] END .....................................n_neighbors=20; total time=   0.1s
[CV] END .....................................n_neighbors=20; total time=   0.1s
[CV] END .....................................n_neighbors=40; total time=   0.1s
[CV] END .....................................n_neighbors=40; total time=   0.1s
[CV] END .....................................n_neighbors=40; total time=   0.1s
[CV] END ....................................n_neighbors=501; total time=   0.5s
[CV] END ....................................n_neighbors=501; total time=   0.5s
[CV] END ....................................n_neighbors=501; total time=   0.5s
Fitting 3 folds for each of 100 candidates, totalling 300 fits
[CV] END max_depth=None, max_features=7, min_samples_split=8, n_estimators=200; total time=   1.2s
[CV] END max_depth=None, max_features=7, min_samples_split=8, n_estimators=200; total time=   1.1s
[CV] END max_depth=None, max_features=7, min_samples_split=8, n_estimators=200; total time=   1.2s
[CV] END max_depth=8, max_features=auto, min_samples_split=15, n_estimators=200; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=15, n_estimators=200; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=15, n_estimators=200; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=20, n_estimators=100; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=20, n_estimators=100; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=20, n_estimators=100; total time=   0.0s
[CV] END max_depth=None, max_features=5, min_samples_split=2, n_estimators=500; total time=   3.0s
[CV] END max_depth=None, max_features=5, min_samples_split=2, n_estimators=500; total time=   3.0s
[CV] END max_depth=None, max_features=5, min_samples_split=2, n_estimators=500; total time=   2.9s
[CV] END max_depth=15, max_features=auto, min_samples_split=20, n_estimators=200; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=20, n_estimators=200; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=20, n_estimators=200; total time=   0.0s
[CV] END max_depth=None, max_features=7, min_samples_split=15, n_estimators=500; total time=   2.6s
[CV] END max_depth=None, max_features=7, min_samples_split=15, n_estimators=500; total time=   2.6s
[CV] END max_depth=None, max_features=7, min_samples_split=15, n_estimators=500; total time=   2.6s
[CV] END max_depth=5, max_features=5, min_samples_split=20, n_estimators=1000; total time=   2.6s
[CV] END max_depth=5, max_features=5, min_samples_split=20, n_estimators=1000; total time=   2.5s
[CV] END max_depth=5, max_features=5, min_samples_split=20, n_estimators=1000; total time=   2.3s
[CV] END max_depth=101, max_features=7, min_samples_split=2, n_estimators=100; total time=   0.7s
[CV] END max_depth=101, max_features=7, min_samples_split=2, n_estimators=100; total time=   0.7s
[CV] END max_depth=101, max_features=7, min_samples_split=2, n_estimators=100; total time=   0.7s
[CV] END max_depth=5, max_features=5, min_samples_split=8, n_estimators=200; total time=   0.5s
[CV] END max_depth=5, max_features=5, min_samples_split=8, n_estimators=200; total time=   0.5s
[CV] END max_depth=5, max_features=5, min_samples_split=8, n_estimators=200; total time=   0.5s
[CV] END max_depth=None, max_features=7, min_samples_split=15, n_estimators=100; total time=   0.5s
[CV] END max_depth=None, max_features=7, min_samples_split=15, n_estimators=100; total time=   0.5s
[CV] END max_depth=None, max_features=7, min_samples_split=15, n_estimators=100; total time=   0.5s
[CV] END max_depth=8, max_features=7, min_samples_split=15, n_estimators=1000; total time=   4.2s
[CV] END max_depth=8, max_features=7, min_samples_split=15, n_estimators=1000; total time=   4.3s
[CV] END max_depth=8, max_features=7, min_samples_split=15, n_estimators=1000; total time=   4.2s
[CV] END max_depth=101, max_features=8, min_samples_split=8, n_estimators=100; total time=   0.7s
[CV] END max_depth=101, max_features=8, min_samples_split=8, n_estimators=100; total time=   0.6s
[CV] END max_depth=101, max_features=8, min_samples_split=8, n_estimators=100; total time=   0.6s
[CV] END max_depth=8, max_features=auto, min_samples_split=15, n_estimators=1000; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=15, n_estimators=1000; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=15, n_estimators=1000; total time=   0.0s
[CV] END max_depth=None, max_features=7, min_samples_split=15, n_estimators=200; total time=   1.1s
[CV] END max_depth=None, max_features=7, min_samples_split=15, n_estimators=200; total time=   1.0s
[CV] END max_depth=None, max_features=7, min_samples_split=15, n_estimators=200; total time=   1.1s
[CV] END max_depth=101, max_features=auto, min_samples_split=8, n_estimators=100; total time=   0.0s
[CV] END max_depth=101, max_features=auto, min_samples_split=8, n_estimators=100; total time=   0.0s
[CV] END max_depth=101, max_features=auto, min_samples_split=8, n_estimators=100; total time=   0.0s
[CV] END max_depth=15, max_features=8, min_samples_split=15, n_estimators=500; total time=   2.9s
[CV] END max_depth=15, max_features=8, min_samples_split=15, n_estimators=500; total time=   2.8s
[CV] END max_depth=15, max_features=8, min_samples_split=15, n_estimators=500; total time=   2.9s
[CV] END max_depth=None, max_features=8, min_samples_split=2, n_estimators=1000; total time=   7.7s
[CV] END max_depth=None, max_features=8, min_samples_split=2, n_estimators=1000; total time=   7.6s
[CV] END max_depth=None, max_features=8, min_samples_split=2, n_estimators=1000; total time=   7.7s
[CV] END max_depth=15, max_features=auto, min_samples_split=2, n_estimators=100; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=2, n_estimators=100; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=2, n_estimators=100; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END max_depth=5, max_features=7, min_samples_split=8, n_estimators=1000; total time=   3.2s
[CV] END max_depth=5, max_features=7, min_samples_split=8, n_estimators=1000; total time=   3.1s
[CV] END max_depth=5, max_features=7, min_samples_split=8, n_estimators=1000; total time=   3.1s
[CV] END max_depth=None, max_features=5, min_samples_split=15, n_estimators=100; total time=   0.4s
[CV] END max_depth=None, max_features=5, min_samples_split=15, n_estimators=100; total time=   0.4s
[CV] END max_depth=None, max_features=5, min_samples_split=15, n_estimators=100; total time=   0.4s
[CV] END max_depth=None, max_features=7, min_samples_split=15, n_estimators=1000; total time=   5.3s
[CV] END max_depth=None, max_features=7, min_samples_split=15, n_estimators=1000; total time=   5.2s
[CV] END max_depth=None, max_features=7, min_samples_split=15, n_estimators=1000; total time=   5.3s
[CV] END max_depth=101, max_features=auto, min_samples_split=20, n_estimators=1000; total time=   0.0s
[CV] END max_depth=101, max_features=auto, min_samples_split=20, n_estimators=1000; total time=   0.0s
[CV] END max_depth=101, max_features=auto, min_samples_split=20, n_estimators=1000; total time=   0.0s
[CV] END max_depth=101, max_features=auto, min_samples_split=15, n_estimators=100; total time=   0.0s
[CV] END max_depth=101, max_features=auto, min_samples_split=15, n_estimators=100; total time=   0.0s
[CV] END max_depth=101, max_features=auto, min_samples_split=15, n_estimators=100; total time=   0.0s
[CV] END max_depth=15, max_features=5, min_samples_split=8, n_estimators=1000; total time=   4.3s
[CV] END max_depth=15, max_features=5, min_samples_split=8, n_estimators=1000; total time=   4.2s
[CV] END max_depth=15, max_features=5, min_samples_split=8, n_estimators=1000; total time=   4.2s
[CV] END max_depth=15, max_features=8, min_samples_split=8, n_estimators=100; total time=   0.6s
[CV] END max_depth=15, max_features=8, min_samples_split=8, n_estimators=100; total time=   0.6s
[CV] END max_depth=15, max_features=8, min_samples_split=8, n_estimators=100; total time=   0.6s
[CV] END max_depth=101, max_features=auto, min_samples_split=20, n_estimators=500; total time=   0.0s
[CV] END max_depth=101, max_features=auto, min_samples_split=20, n_estimators=500; total time=   0.0s
[CV] END max_depth=101, max_features=auto, min_samples_split=20, n_estimators=500; total time=   0.0s
[CV] END max_depth=8, max_features=7, min_samples_split=2, n_estimators=100; total time=   0.4s
[CV] END max_depth=8, max_features=7, min_samples_split=2, n_estimators=100; total time=   0.4s
[CV] END max_depth=8, max_features=7, min_samples_split=2, n_estimators=100; total time=   0.4s
[CV] END max_depth=None, max_features=5, min_samples_split=15, n_estimators=200; total time=   0.8s
[CV] END max_depth=None, max_features=5, min_samples_split=15, n_estimators=200; total time=   0.8s
[CV] END max_depth=None, max_features=5, min_samples_split=15, n_estimators=200; total time=   0.8s
[CV] END max_depth=15, max_features=7, min_samples_split=8, n_estimators=1000; total time=   5.4s
[CV] END max_depth=15, max_features=7, min_samples_split=8, n_estimators=1000; total time=   5.3s
[CV] END max_depth=15, max_features=7, min_samples_split=8, n_estimators=1000; total time=   5.4s
[CV] END max_depth=5, max_features=auto, min_samples_split=2, n_estimators=100; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=2, n_estimators=100; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=2, n_estimators=100; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=8, n_estimators=200; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=8, n_estimators=200; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=8, n_estimators=200; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=8, n_estimators=1000; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=8, n_estimators=1000; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=8, n_estimators=1000; total time=   0.0s
[CV] END max_depth=101, max_features=8, min_samples_split=15, n_estimators=500; total time=   2.9s
[CV] END max_depth=101, max_features=8, min_samples_split=15, n_estimators=500; total time=   2.8s
[CV] END max_depth=101, max_features=8, min_samples_split=15, n_estimators=500; total time=   2.9s
[CV] END max_depth=8, max_features=8, min_samples_split=20, n_estimators=1000; total time=   4.6s
[CV] END max_depth=8, max_features=8, min_samples_split=20, n_estimators=1000; total time=   4.6s
[CV] END max_depth=8, max_features=8, min_samples_split=20, n_estimators=1000; total time=   4.6s
[CV] END max_depth=101, max_features=7, min_samples_split=2, n_estimators=1000; total time=   7.1s
[CV] END max_depth=101, max_features=7, min_samples_split=2, n_estimators=1000; total time=   6.9s
[CV] END max_depth=101, max_features=7, min_samples_split=2, n_estimators=1000; total time=   7.0s
[CV] END max_depth=None, max_features=5, min_samples_split=8, n_estimators=200; total time=   0.9s
[CV] END max_depth=None, max_features=5, min_samples_split=8, n_estimators=200; total time=   0.9s
[CV] END max_depth=None, max_features=5, min_samples_split=8, n_estimators=200; total time=   0.9s
[CV] END max_depth=8, max_features=8, min_samples_split=20, n_estimators=500; total time=   2.4s
[CV] END max_depth=8, max_features=8, min_samples_split=20, n_estimators=500; total time=   2.3s
[CV] END max_depth=8, max_features=8, min_samples_split=20, n_estimators=500; total time=   2.3s
[CV] END max_depth=15, max_features=8, min_samples_split=2, n_estimators=100; total time=   0.7s
[CV] END max_depth=15, max_features=8, min_samples_split=2, n_estimators=100; total time=   0.7s
[CV] END max_depth=15, max_features=8, min_samples_split=2, n_estimators=100; total time=   0.7s
[CV] END max_depth=15, max_features=auto, min_samples_split=20, n_estimators=500; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=20, n_estimators=500; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=20, n_estimators=500; total time=   0.0s
[CV] END max_depth=None, max_features=5, min_samples_split=15, n_estimators=1000; total time=   4.2s
[CV] END max_depth=None, max_features=5, min_samples_split=15, n_estimators=1000; total time=   4.0s
[CV] END max_depth=None, max_features=5, min_samples_split=15, n_estimators=1000; total time=   4.1s
[CV] END max_depth=5, max_features=8, min_samples_split=15, n_estimators=1000; total time=   3.3s
[CV] END max_depth=5, max_features=8, min_samples_split=15, n_estimators=1000; total time=   3.3s
[CV] END max_depth=5, max_features=8, min_samples_split=15, n_estimators=1000; total time=   3.4s
[CV] END max_depth=8, max_features=7, min_samples_split=20, n_estimators=100; total time=   0.4s
[CV] END max_depth=8, max_features=7, min_samples_split=20, n_estimators=100; total time=   0.4s
[CV] END max_depth=8, max_features=7, min_samples_split=20, n_estimators=100; total time=   0.4s
[CV] END max_depth=8, max_features=8, min_samples_split=15, n_estimators=1000; total time=   4.6s
[CV] END max_depth=8, max_features=8, min_samples_split=15, n_estimators=1000; total time=   4.5s
[CV] END max_depth=8, max_features=8, min_samples_split=15, n_estimators=1000; total time=   4.5s
[CV] END max_depth=101, max_features=7, min_samples_split=15, n_estimators=1000; total time=   5.3s
[CV] END max_depth=101, max_features=7, min_samples_split=15, n_estimators=1000; total time=   5.3s
[CV] END max_depth=101, max_features=7, min_samples_split=15, n_estimators=1000; total time=   5.4s
[CV] END max_depth=None, max_features=auto, min_samples_split=20, n_estimators=500; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=20, n_estimators=500; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=20, n_estimators=500; total time=   0.0s
[CV] END max_depth=101, max_features=8, min_samples_split=15, n_estimators=100; total time=   0.6s
[CV] END max_depth=101, max_features=8, min_samples_split=15, n_estimators=100; total time=   0.6s
[CV] END max_depth=101, max_features=8, min_samples_split=15, n_estimators=100; total time=   0.6s
[CV] END max_depth=5, max_features=auto, min_samples_split=15, n_estimators=100; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=15, n_estimators=100; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=15, n_estimators=100; total time=   0.0s
[CV] END max_depth=15, max_features=5, min_samples_split=15, n_estimators=1000; total time=   4.0s
[CV] END max_depth=15, max_features=5, min_samples_split=15, n_estimators=1000; total time=   4.1s
[CV] END max_depth=15, max_features=5, min_samples_split=15, n_estimators=1000; total time=   4.1s
[CV] END max_depth=101, max_features=auto, min_samples_split=15, n_estimators=1000; total time=   0.0s
[CV] END max_depth=101, max_features=auto, min_samples_split=15, n_estimators=1000; total time=   0.0s
[CV] END max_depth=101, max_features=auto, min_samples_split=15, n_estimators=1000; total time=   0.0s
[CV] END max_depth=101, max_features=7, min_samples_split=8, n_estimators=500; total time=   2.9s
[CV] END max_depth=101, max_features=7, min_samples_split=8, n_estimators=500; total time=   2.9s
[CV] END max_depth=101, max_features=7, min_samples_split=8, n_estimators=500; total time=   3.0s
[CV] END max_depth=8, max_features=7, min_samples_split=8, n_estimators=500; total time=   2.1s
[CV] END max_depth=8, max_features=7, min_samples_split=8, n_estimators=500; total time=   2.0s
[CV] END max_depth=8, max_features=7, min_samples_split=8, n_estimators=500; total time=   2.3s
[CV] END max_depth=8, max_features=8, min_samples_split=8, n_estimators=200; total time=   1.0s
[CV] END max_depth=8, max_features=8, min_samples_split=8, n_estimators=200; total time=   1.0s
[CV] END max_depth=8, max_features=8, min_samples_split=8, n_estimators=200; total time=   1.0s
[CV] END max_depth=101, max_features=5, min_samples_split=8, n_estimators=200; total time=   0.9s
[CV] END max_depth=101, max_features=5, min_samples_split=8, n_estimators=200; total time=   0.9s
[CV] END max_depth=101, max_features=5, min_samples_split=8, n_estimators=200; total time=   0.9s
[CV] END max_depth=101, max_features=5, min_samples_split=2, n_estimators=500; total time=   2.8s
[CV] END max_depth=101, max_features=5, min_samples_split=2, n_estimators=500; total time=   2.8s
[CV] END max_depth=101, max_features=5, min_samples_split=2, n_estimators=500; total time=   2.8s
[CV] END max_depth=101, max_features=8, min_samples_split=20, n_estimators=200; total time=   1.1s
[CV] END max_depth=101, max_features=8, min_samples_split=20, n_estimators=200; total time=   1.1s
[CV] END max_depth=101, max_features=8, min_samples_split=20, n_estimators=200; total time=   1.1s
[CV] END max_depth=15, max_features=7, min_samples_split=15, n_estimators=200; total time=   1.0s
[CV] END max_depth=15, max_features=7, min_samples_split=15, n_estimators=200; total time=   1.0s
[CV] END max_depth=15, max_features=7, min_samples_split=15, n_estimators=200; total time=   1.1s
[CV] END max_depth=15, max_features=7, min_samples_split=20, n_estimators=1000; total time=   5.5s
[CV] END max_depth=15, max_features=7, min_samples_split=20, n_estimators=1000; total time=   5.0s
[CV] END max_depth=15, max_features=7, min_samples_split=20, n_estimators=1000; total time=   5.2s
[CV] END max_depth=15, max_features=5, min_samples_split=2, n_estimators=1000; total time=   5.0s
[CV] END max_depth=15, max_features=5, min_samples_split=2, n_estimators=1000; total time=   5.2s
[CV] END max_depth=15, max_features=5, min_samples_split=2, n_estimators=1000; total time=   4.9s
[CV] END max_depth=15, max_features=auto, min_samples_split=15, n_estimators=500; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=15, n_estimators=500; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=15, n_estimators=500; total time=   0.0s
[CV] END max_depth=15, max_features=8, min_samples_split=8, n_estimators=200; total time=   1.2s
[CV] END max_depth=15, max_features=8, min_samples_split=8, n_estimators=200; total time=   1.2s
[CV] END max_depth=15, max_features=8, min_samples_split=8, n_estimators=200; total time=   1.2s
[CV] END max_depth=101, max_features=5, min_samples_split=15, n_estimators=100; total time=   0.4s
[CV] END max_depth=101, max_features=5, min_samples_split=15, n_estimators=100; total time=   0.4s

### Model Re-Trainig 

- Fine tuning with the best parameters after Hyper Parameter Tuning

In [33]:
models_best_params = {
    "K Nearest Neighbours": KNeighborsRegressor(n_neighbors=10),
    "Random Forest Regression": RandomForestRegressor(n_estimators=100, min_samples_split=2, max_features=5, max_depth=101),
    "Adaboost Regressor": AdaBoostRegressor(n_estimators=60, loss='linear')
}

for i in range(len(list(models_best_params))):
    model = list(models_best_params.values())[i]
    model.fit(X_train,y_train)          # Train Model

    ## Prediction
    y_train_prediction = model.predict(X_train)
    y_test_prediction = model.predict(X_test)

    ## Evaluate Model
    mse_train, mae_train, rmse_train, r2_scr_train = evaluate_model(y_train, y_train_prediction)
    mse_test, mae_test, rmse_test, r2_scr_test = evaluate_model(y_test, y_test_prediction)

    print(list(models_best_params.keys())[i])

    print("-"*35)

    print("Model Performance for Training dataset")
    print("- Mean Squared Error: {:.2f}".format(mse_train))
    print("- Mean Absolute Error: {:.2f}".format(mae_train))
    print("- Root Mean Squared Error: {:.2f}".format(rmse_train))
    print("- R2 Score: {:.2f}".format(r2_scr_train))

    print("-"*35)

    print("Model Performance for Test dataset")
    print("- Mean Squared Error: {:.2f}".format(mse_test))
    print("- Mean Absolute Error: {:.2f}".format(mae_test))
    print("- Root Mean Squared Error: {:.2f}".format(rmse_test))
    print("- R2 Score: {:.2f}".format(r2_scr_test))
    print("-"*35)
    print("\n")

K Nearest Neighbours
-----------------------------------
Model Performance for Training dataset
- Mean Squared Error: 132092084047.70
- Mean Absolute Error: 103456.46
- Root Mean Squared Error: 363444.75
- R2 Score: 0.84
-----------------------------------
Model Performance for Test dataset
- Mean Squared Error: 69620968665.46
- Mean Absolute Error: 117432.90
- Root Mean Squared Error: 263857.86
- R2 Score: 0.91
-----------------------------------


Random Forest Regression
-----------------------------------
Model Performance for Training dataset
- Mean Squared Error: 17741935399.03
- Mean Absolute Error: 39431.41
- Root Mean Squared Error: 133198.86
- R2 Score: 0.98
-----------------------------------
Model Performance for Test dataset
- Mean Squared Error: 41987633270.72
- Mean Absolute Error: 97381.46
- Root Mean Squared Error: 204908.84
- R2 Score: 0.94
-----------------------------------


Adaboost Regressor
-----------------------------------
Model Performance for Training dataset
- Mean Squared Error: 151000301868.21
- Mean Absolute Error: 261913.75
- Root Mean Squared Error: 388587.57
- R2 Score: 0.81
-----------------------------------
Model Performance for Test dataset
- Mean Squared Error: 175235620344.49
- Mean Absolute Error: 280460.68
- Root Mean Squared Error: 418611.54
- R2 Score: 0.77
-----------------------------------